package ndk.banee.spring_jstore.mapper;

import ndk.banee.spring_jstore.domain.wishlist;
import ndk.banee.spring_jstore.domain.wishlistExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface wishlistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbg.generated Mon Jun 01 21:28:37 CST 2020
     */
    long countByExample(wishlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbg.generated Mon Jun 01 21:28:37 CST 2020
     */
    int deleteByExample(wishlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbg.generated Mon Jun 01 21:28:37 CST 2020
     */
    int deleteByPrimaryKey(Integer wishlistid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbg.generated Mon Jun 01 21:28:37 CST 2020
     */
    int insert(wishlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbg.generated Mon Jun 01 21:28:37 CST 2020
     */
    int insertSelective(wishlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbg.generated Mon Jun 01 21:28:37 CST 2020
     */
    List<wishlist> selectByExample(wishlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbg.generated Mon Jun 01 21:28:37 CST 2020
     */
    wishlist selectByPrimaryKey(Integer wishlistid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbg.generated Mon Jun 01 21:28:37 CST 2020
     */
    int updateByExampleSelective(@Param("record") wishlist record, @Param("example") wishlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbg.generated Mon Jun 01 21:28:37 CST 2020
     */
    int updateByExample(@Param("record") wishlist record, @Param("example") wishlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbg.generated Mon Jun 01 21:28:37 CST 2020
     */
    int updateByPrimaryKeySelective(wishlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbg.generated Mon Jun 01 21:28:37 CST 2020
     */
    int updateByPrimaryKey(wishlist record);
}
